### PR TITLE
Named Locations missing from export

### PR DESCRIPTION
**Pull request by mr-cop**
Named Locations were missing from export when you selected **CSV** or **HTML** and also when **All** was selected the Named Locations were not exported in HTML.

### CODE REVIEW

**Review by Donovand4 — CHANGES_REQUESTED** [review]
The replace method in the HTML section completely removes the conditional access policies from the html file. It would need to be added as a new region underneath the CA policies.

**Comment by mr-cop** [comment]
At the moment with my mods the CAPs and NLs are generated separately in every situation. There will be an html file for CAPs and an HTML file for Named Locations. i can add an option to combine output in different sections? or do you want that to be the default?
in the current case, the -All option will result in two separate files, or, we could add a -Unify option to have a single file with two sections instead or make this the default?

**Comment by Donovand4** [comment]
I like the idea of a defaulted combined HTML, it would be great for the user experience, and allow for separate csv files for each one to be exported.

**Comment by Donovand4** [comment]
Updated the script to export named locations and CA policies to one html file with formating.

**Pull request closed without merging**
